import {readFile, writeFile} from "node:fs/promises";

import {OVSDBClient} from "./index";
import type {OvsdbClientOptions} from "./index";
import type {AtomicType, BaseType, DatabaseSchema, JsonValue} from "./types";

/**
 * Options for generating TypeScript types from an OVSDB schema.
 */
export interface GenerateTypesOptions {
    /**
     * The schema object to transform.
     */
    schema: DatabaseSchema;

    /**
     * Name of the generated top-level database type.
     *
     * @defaultValue Derived from `schema.name`
     */
    databaseTypeName?: string;

    /**
     * Module specifier used in generated imports.
     *
     * @defaultValue `"@sourceregistry/node-ovsdb"`
     */
    importFrom?: string;
}

/**
 * CLI options for reading a schema and writing generated types.
 */
export interface GenerateTypesCliOptions {
    /**
     * Path to a schema JSON file. When set, live OVSDB access is skipped.
     */
    schemaPath?: string;

    /**
     * Unix socket path for live schema introspection.
     */
    socketPath?: string;

    /**
     * Hostname for live schema introspection over TCP or TLS.
     */
    host?: string;

    /**
     * Port for live schema introspection over TCP or TLS.
     *
     * @defaultValue `6640`
     */
    port?: number;

    /**
     * Enables TLS for live schema introspection.
     */
    tls?: boolean;

    /**
     * Disables TLS peer verification for environments that use self-signed certificates.
     */
    tlsInsecure?: boolean;

    /**
     * Explicit TLS server name used during handshake verification.
     */
    tlsServername?: string;

    /**
     * PEM CA bundle path used for TLS verification.
     */
    tlsCaFile?: string;

    /**
     * PEM client certificate path used for mutual TLS.
     */
    tlsCertFile?: string;

    /**
     * PEM client private key path used for mutual TLS.
     */
    tlsKeyFile?: string;

    /**
     * Database name used with live schema introspection.
     *
     * @defaultValue `"Open_vSwitch"`
     */
    databaseName?: string;

    /**
     * Destination file. When omitted, generated output is returned only.
     */
    outputPath?: string;

    /**
     * Name of the generated top-level database type.
     */
    databaseTypeName?: string;

    /**
     * Module specifier used in generated imports.
     *
     * @defaultValue `"@sourceregistry/node-ovsdb"`
     */
    importFrom?: string;
}

const OVSDB_IMPORT_TYPES = ["OvsMap", "OvsSet", "Uuid"] as const;

/**
 * Generates TypeScript types from an OVSDB schema.
 *
 * The output is designed for direct use as the generic database model for
 * {@link OVSDBClient}.
 */
export function generateTypesFromSchema(options: GenerateTypesOptions): string {
    const {schema} = options;
    const importFrom = options.importFrom ?? "@sourceregistry/node-ovsdb";
    const databaseTypeName = options.databaseTypeName ?? `${toPascalCase(schema.name)}Database`;

    const importLine = `import type {${OVSDB_IMPORT_TYPES.join(", ")}} from "${importFrom}";`;

    const tableNames = Object.keys(schema.tables).sort((left, right) => left.localeCompare(right));
    const rowInterfaces = tableNames.map((tableName) => {
        const interfaceName = `${toPascalCase(tableName)}Row`;
        const table = schema.tables[tableName];
        const propertyLines = Object.keys(table.columns)
            .sort((left, right) => left.localeCompare(right))
            .map((columnName) => {
                const column = table.columns[columnName];
                const tsType = renderColumnType(column.type);
                const optional = isOptionalColumn(column.type) ? "?" : "";
                return `    ${toPropertyKey(columnName)}${optional}: ${tsType};`;
            });

        return [
            `/**`,
            ` * Row model for the \`${tableName}\` table in the \`${schema.name}\` schema.`,
            ` */`,
            `export interface ${interfaceName} {`,
            ...propertyLines,
            `}`
        ].join("\n");
    });

    const databaseLines = [
        `/**`,
        ` * Generated database model for the \`${schema.name}\` schema.`,
        ` */`,
        `export interface ${databaseTypeName} {`,
        ...tableNames.map((tableName) => `    ${toPropertyKey(tableName)}: ${toPascalCase(tableName)}Row;`),
        `}`
    ];

    const tableNamesConst = [
        `/**`,
        ` * Table names available in the \`${schema.name}\` schema.`,
        ` */`,
        `export const ${databaseTypeName}TableNames = ${JSON.stringify(tableNames)} as const;`
    ];

    return [
        `/* eslint-disable */`,
        `/*`,
        ` * This file was generated by ovsdb-generate.`,
        ` * Schema: ${schema.name}@${schema.version}`,
        ` */`,
        "",
        importLine,
        "",
        ...rowInterfaces.flatMap((block) => [block, ""]),
        ...databaseLines,
        "",
        ...tableNamesConst
    ].join("\n").trimEnd() + "\n";
}

/**
 * Loads a schema from a file or a live OVSDB server and optionally writes the
 * generated TypeScript output to disk.
 */
export async function generateTypesFile(options: GenerateTypesCliOptions): Promise<string> {
    const schema = await loadSchema(options);
    const output = generateTypesFromSchema({
        schema,
        databaseTypeName: options.databaseTypeName,
        importFrom: options.importFrom
    });

    if (options.outputPath) {
        await writeFile(options.outputPath, output, "utf8");
    }

    return output;
}

/**
 * Reads a schema JSON file from disk.
 */
export async function readSchemaFile(schemaPath: string): Promise<DatabaseSchema> {
    const raw = await readFile(schemaPath, "utf8");
    return JSON.parse(raw) as DatabaseSchema;
}

/**
 * Reads a schema from a live OVSDB server.
 */
export async function fetchSchemaFromOvsdb(options: {
    socketPath?: string;
    host?: string;
    port?: number;
    tls?: boolean;
    tlsInsecure?: boolean;
    tlsServername?: string;
    tlsCaFile?: string;
    tlsCertFile?: string;
    tlsKeyFile?: string;
    databaseName?: string;
}): Promise<DatabaseSchema> {
    const client = new OVSDBClient(await createGeneratorClientOptions(options));

    try {
        await client.connect();
        return await client.getSchema(options.databaseName ?? "Open_vSwitch");
    } finally {
        await client.close();
    }
}

async function loadSchema(options: GenerateTypesCliOptions): Promise<DatabaseSchema> {
    if (options.schemaPath) {
        return await readSchemaFile(options.schemaPath);
    }

    return await fetchSchemaFromOvsdb({
        socketPath: options.socketPath,
        host: options.host,
        port: options.port,
        tls: options.tls,
        tlsInsecure: options.tlsInsecure,
        tlsServername: options.tlsServername,
        tlsCaFile: options.tlsCaFile,
        tlsCertFile: options.tlsCertFile,
        tlsKeyFile: options.tlsKeyFile,
        databaseName: options.databaseName
    });
}

/**
 * Builds client transport options for live schema introspection.
 */
export async function createGeneratorClientOptions(options: {
    socketPath?: string;
    host?: string;
    port?: number;
    tls?: boolean;
    tlsInsecure?: boolean;
    tlsServername?: string;
    tlsCaFile?: string;
    tlsCertFile?: string;
    tlsKeyFile?: string;
}): Promise<OvsdbClientOptions> {
    if (!options.host) {
        return {
            socketPath: options.socketPath
        };
    }

    return {
        host: options.host,
        port: options.port,
        tls: options.tls,
        tlsOptions: {
            servername: options.tlsServername ?? options.host,
            rejectUnauthorized: options.tlsInsecure ? false : undefined,
            ca: options.tlsCaFile ? await readFile(options.tlsCaFile, "utf8") : undefined,
            cert: options.tlsCertFile ? await readFile(options.tlsCertFile, "utf8") : undefined,
            key: options.tlsKeyFile ? await readFile(options.tlsKeyFile, "utf8") : undefined
        }
    };
}

function renderColumnType(type: DatabaseSchema["tables"][string]["columns"][string]["type"]): string {
    if (typeof type === "string") {
        return renderAtomicType(type);
    }

    if ("value" in type && type.value !== undefined) {
        return `OvsMap<${renderBaseType(type.key)}, ${renderBaseType(type.value)}>`;
    }

    if (isScalarType(type)) {
        return renderBaseType(type.key);
    }

    return `OvsSet<${renderBaseType(type.key)}>`;
}

function isOptionalColumn(type: DatabaseSchema["tables"][string]["columns"][string]["type"]): boolean {
    if (typeof type === "string") {
        return false;
    }

    return type.min === 0;
}

function isScalarType(type: Extract<DatabaseSchema["tables"][string]["columns"][string]["type"], {key: BaseType}>): boolean {
    const min = type.min ?? 1;
    const max = type.max ?? 1;
    return min === 1 && max === 1;
}

function renderBaseType(baseType: BaseType): string {
    if (typeof baseType === "string") {
        return renderAtomicType(baseType);
    }

    if (baseType.enum) {
        return renderEnum(baseType.enum);
    }

    return renderAtomicType(baseType.type);
}

function renderAtomicType(type: AtomicType): string {
    switch (type) {
        case "integer":
        case "real":
            return "number";
        case "boolean":
            return "boolean";
        case "string":
            return "string";
        case "uuid":
            return "Uuid";
        default:
            return "unknown";
    }
}

function renderEnum(value: JsonValue): string {
    if (Array.isArray(value) && value[0] === "set" && Array.isArray(value[1])) {
        const members = value[1]
            .map((member) => typeof member === "string" ? JSON.stringify(member) : renderJsonValue(member))
            .join(" | ");
        return members || "never";
    }

    return renderJsonValue(value);
}

function renderJsonValue(value: JsonValue): string {
    return JSON.stringify(value);
}

function toPascalCase(value: string): string {
    return value
        .replace(/[^a-zA-Z0-9]+/g, " ")
        .split(" ")
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join("");
}

function toPropertyKey(value: string): string {
    return /^[$A-Z_][0-9A-Z_$]*$/i.test(value) ? value : JSON.stringify(value);
}
